In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("weather_forecast_data.csv")
df.head()

   Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0    23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1    27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2    25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3    23.622080  74.367758    7.050551    67.255282   982.632013     rain
4    20.591370  96.858822    4.643921    47.676444   980.825142  no rain

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  2500 non-null   float64
 1   Humidity     2500 non-null   float64
 2   Wind_Speed   2500 non-null   float64
 3   Cloud_Cover  2500 non-null   float64
 4   Pressure     2500 non-null   float64
 5   Rain         2500 non-null   object
dtypes: float64(5), object(1)
memory usage: 117.3+ KB

In [4]:
df.shape

(2500, 6)

In [5]:
df.describe()

       Temperature     Humidity   Wind_Speed  Cloud_Cover     Pressure
count  2500.000000  2500.000000  2500.000000  2500.000000  2500.000000
mean     22.581725    64.347094     9.906255    49.658104  1014.312336
std       7.326996    19.954739     5.780316    29.123104    20.196433
min      10.001842    30.005071     0.009819     0.015038   980.014486
25%      16.359398    47.339815     4.761909    23.900016   996.938630
50%      22.536448    63.920797     9.908572    49.488284  1013.433035
75%      28.976476    81.561021    14.948408    75.324140  1031.735067
max      34.995214    99.997481    19.999132    99.997795  1049.985593

In [6]:
df.isnull().sum()

Temperature    0
Humidity       0
Wind_Speed     0
Cloud_Cover    0
Pressure       0
Rain           0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Rain'] = le.fit_transform(df['Rain'])
df

      Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure  Rain
0       23.720338  89.592641    7.335604    50.501694  1032.378759     1
1       27.879734  46.489704    5.952484     4.990053   992.614190     0
2       25.069084  83.072843    1.371992    14.855784  1007.231620     0
3       23.622080  74.367758    7.050551    67.255282   982.632013     1
4       20.591370  96.858822    4.643921    47.676444   980.825142     0
...           ...        ...         ...          ...          ...   ...
2495    21.791602  45.270902   11.807192    55.044682  1017.686181     0
2496    27.558479  46.481744   10.884915    39.715133  1008.590961     0
2497    28.108274  43.817178    2.897128    75.842952   999.119187     0
2498    14.789275  57.908105    2.374717     2.378743  1046.501875     0
2499    26.554356  97.101517   18.563084    81.357508  1001.729176     0

[2500 rows x 6 columns]

In [8]:
X = df.drop('Rain',axis = 1)
y = df['Rain']

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
Xscaled = scaler.fit_transform(X)

In [14]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest = train_test_split(Xscaled,y,test_size = 0.2,random_state=42)

In [15]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear')
svc.fit(Xtrain,ytrain)

SVC(kernel='linear')

In [16]:
ypred = svc.predict(Xtest)

In [25]:
from sklearn.metrics import accuracy_score, classification_report

cr = classification_report(ytest,ypred)

In [26]:
cr

'              precision    recall  f1-score   support\n\n           0       0.95      0.97      0.96       443\n           1       0.73      0.61      0.67        57\n\n    accuracy                           0.93       500\n   macro avg       0.84      0.79      0.81       500\nweighted avg       0.93      0.93      0.93       500\n'

In [27]:
acc = accuracy_score(ytest,ypred)
acc

0.93