In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df = df.drop(columns=['Id'], errors='ignore')
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
X = df.drop('Species', axis=1)
y = df['Species']

In [7]:
from sklearn.model_selection import train_test_split 
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

best_k = None
best_acc = 0
for i in range(20):
    k = np.random.randint(1,20)
    model = KNeighborsClassifier(n_neighbors = k)
    model.fit(Xtrain,ytrain)

    ypred = model.predict(Xtest)
    acc = accuracy_score(ytest,ypred)

    print(f"trail{i+1} k= {k} acc = {acc} ")

    if acc > best_acc:
        best_acc = acc
        best_k = k

print(best_k)
print(best_acc)

trail1 k= 18 acc = 1.0
trail2 k= 11 acc = 1.0
trail3 k= 14 acc = 1.0
trail4 k= 16 acc = 1.0
trail5 k= 8 acc = 1.0
trail6 k= 1 acc = 1.0
trail7 k= 8 acc = 1.0
trail8 k= 15 acc = 1.0
trail9 k= 5 acc = 1.0
trail10 k= 13 acc = 1.0
trail11 k= 9 acc = 1.0
trail12 k= 7 acc = 0.9666666666666667
trail13 k= 7 acc = 0.9666666666666667
trail14 k= 12 acc = 1.0
trail15 k= 1 acc = 1.0
trail16 k= 7 acc = 0.9666666666666667
trail17 k= 11 acc = 1.0
trail18 k= 5 acc = 1.0
trail19 k= 18 acc = 1.0
trail20 k= 9 acc = 1.0
18
1.0